name: dyjs0

on:
  workflow_dispatch:
  schedule:
     - cron: '48 0 * * *'

  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    env:
        DYJS_S_URL: ${{ secrets.DYJS_S_URL }}
        DYJS_V_URL: ${{ secrets.DYJS_V_URL }}
        DYJS_INFO_URL: ${{ secrets.DYJS_INFO_URL }}
        DYJS_S_HD: ${{ secrets.DYJS_S_HD }}
        DYJS_V_HD: ${{ secrets.DYJS_V_HD }}
        DYJS_INFO_HD: ${{ secrets.DYJS_INFO_HD }}
        DYJS_BD: ${{ secrets.DYJS_BD }}    
        TZ: Asia/shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: |
          npm install
          
      - name: '运行 【dyjs0】'
        if: env.DYJS_S_HD
        run: |
          node dyjs/dyjs0.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
